name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 mypy

    - name: Lint with flake8
      run: flake8 httpd.py handler.py tests/

    - name: Type check with mypy
      run: mypy httpd.py handler.py

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t simple_http_server .

    - name: Test Docker container
      run: |
        docker run -d -p 8080:8080 simple_http_server
        sleep 5
        curl -f http://localhost:8080/ || exit 1
        docker stop $(docker ps -q --filter ancestor=simple_http_server)
